### ISSUE TITLE
DeprecationWarning about collections.abc

### ISSUE THREAD

**Issue by Gallaecio** [pyeve/cerberus#450]
Pytest reports the following deprecation warnings about Cerberus 1.2 under Python 3.7:

```
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Hashable, Iterable, Mapping, Sequence

/usr/local/lib/python3.7/site-packages/cerberus/schema.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import (Callable, Hashable, Iterable, Mapping,
```

**Comment by funkyfuture** [comment]
thanks for the hint. it would be super helpful to know when the classes in question had been introduced to the `collections.abc` module to consider this in the development roadmap.

sidenote: this is already resolved on my `forward` branch (#431) that drafts the 2.x branch.

**Comment by Gallaecio** [comment]
> Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.

@ https://docs.python.org/3/library/collections.html

**Comment by garbageek** [comment]
Issue still active. Do you plan release minor update. 
Looks like it is well known problem:
 https://github.com/pyparsing/pyparsing/pull/16/commits/cab6d89801635efca99ded91e5a5e1e829f33876

**Comment by funkyfuture** [comment]
i'm reopening the issue for visibilty until the new releases are out.

**Comment by funkyfuture** [comment]
a new release is out, be aware that is has minor, [known flaws](https://github.com/pyeve/cerberus/milestone/8=closed=1).
